os: linux
dist: bionic
language: c

addons:
  apt:
    packages:
    - autopoint

matrix:
  include:
    # Linux - amd64
    - env: BRANCH=0.20.2
    - env: BRANCH=1.0.8
    - env: BRANCH=1.2.6
    - env: BRANCH=devel

    # Linux - arm64
    - arch: arm64
      env: BRANCH=1.2.6

    # Linux - ppc64
    - arch: ppc64le
      env: BRANCH=1.2.6

    # macOS - amd64
    - os: osx
      env: BRANCH=0.20.2
    - os: osx
      env: BRANCH=1.0.8
    - os: osx
      env: BRANCH=1.2.6
    - os: osx
      env: BRANCH=devel

    # windows - amd64
    - os: windows
      env: BRANCH=0.20.2
    - os: windows
      env: BRANCH=1.0.8
    - os: windows
      env: BRANCH=1.2.6
    - os: windows
      env: BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim"

install:
  - export PATH="/usr/local/opt/gettext/bin:$PATH"
  - curl https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/raw/travis.sh -LsSf -o travis.sh
  - source travis.sh

script:
  - set -e
  - nimble develop -y
  - nimble test
  - nimble --verbose --nimbleDir:`pwd`/build/fakenimble install nimterop@#head -y
