os:
  - linux
  - osx

addons:
  apt:
    packages:
    - autopoint

language: c

env:
  - BRANCH=0.19.6
  - BRANCH=0.20.2
  - BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim/toolchains/nim-0.19.6"
    - "$HOME/.choosenim/toolchains/nim-0.20.2"

install:
  - set -e
  - export CHOOSENIM_CHOOSE_VERSION=$BRANCH
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH

script:
  - set -e
  - nimble --verbose install -y
  - nimble --verbose test
  - nimble --verbose --nimbleDir:`pwd`/build/fakenimble install nimterop -y
