version: '{build}'

image:
  - Visual Studio 2015
  - Ubuntu

matrix:
  fast_finish: true

environment:
  matrix:
    - NIM_VERSION: 0.20.2
    - NIM_VERSION: 1.0.4

for:
-
  matrix:
    only:
      - image: Visual Studio 2015

  environment:
    ARCH: 64
    GIT_URL: https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/
    GIT_ARCHIVE: PortableGit-2.23.0-64-bit.7z.exe

  install:
    - CD c:\
    - IF not exist "binaries" (
      echo %NIM_VERSION% &&
      MKDIR binaries &&
      CD binaries &&
      MKDIR git &&
      CD git &&
      appveyor DownloadFile "%GIT_URL%/%GIT_ARCHIVE%" -FileName "%GIT_ARCHIVE%" &&
      7z x -y -bd "%GIT_ARCHIVE%"> nul &&
      del "%GIT_ARCHIVE%" &&
      CD .. &&
      appveyor DownloadFile "https://nim-lang.org/download/nim-%NIM_VERSION%_x%ARCH%.zip" -FileName "nim-%NIM_VERSION%_x%ARCH%.zip" &&
      7z x -y "nim-%NIM_VERSION%_x%ARCH%.zip"> nul &&
      del "nim-%NIM_VERSION%_x%ARCH%.zip")
    - SET PATH=c:\binaries\git\bin;C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;c:\binaries\nim-%NIM_VERSION%\bin;%USERPROFILE%\.nimble\bin;%PATH%
    - CD %APPVEYOR_BUILD_FOLDER%

# on_finish:
#   - 7z a -r buildlogs-win-pkgs.zip %USERPROFILE%\.nimble\pkgs
#   - appveyor PushArtifact buildlogs-win-pkgs.zip
#   - 7z a -r buildlogs-win-projects.zip c:\projects\*
#   - appveyor PushArtifact buildlogs-win-projects.zip

  cache:
    - c:\binaries

-
  matrix:
    only:
      - image: Ubuntu

  install:
    - sudo apt-get update
    - sudo apt-get --yes --force-yes install liblzma-dev liblzma5 autopoint
    - if [ ! -e /home/appveyor/binaries ]; then
        echo $NIM_VERSION &&
        mkdir /home/appveyor/binaries &&
        cd /home/appveyor/binaries &&
        curl -s -o nim-$NIM_VERSION.tar.xz https://nim-lang.org/download/nim-$NIM_VERSION.tar.xz &&
        tar xJf nim-$NIM_VERSION.tar.xz &&
        cd nim-$NIM_VERSION &&
        sh build.sh &&
        bin/nim c -d:release koch &&
        ./koch boot -d:release &&
        ./koch nimble -d:release;
      fi
    - export PATH=/home/appveyor/binaries/nim-$NIM_VERSION/bin:~/.nimble/bin:$PATH
    - cd $APPVEYOR_BUILD_FOLDER

# on_finish:
#   - zip -r -q buildlogs-lin-pkgs.zip ~/.nimble/pkgs
#   - appveyor PushArtifact buildlogs-lin-pkgs.zip
#   - zip -r -q buildlogs-lin-projects.zip /home/appveyor/projects
#   - appveyor PushArtifact buildlogs-lin-projects.zip

  cache:
  - /home/appveyor/binaries

build_script:
  - nimble --verbose install -y

test_script:
  - nimble --verbose test
  - nimble --verbose --nimbleDir:test install nimterop -y

deploy: off
